
# Create image base on the official Node 10 from dockerhub
FROM node:16.10 as build
# Create app directory in docker container
RUN mkdir -p /usr/local/app

# Change directory to run commands in it
WORKDIR /usr/local/app

# Copy dependency definitions
COPY package*.json /usr/local/app/


# Install dependencies
RUN npm install

# Install angular-cli
RUN npm i -g "@angular/cli@latest"

# Copy all the code
COPY . /usr/local/app/


# Build angular app
# Uncomment for production build
#RUN npm run build

# Development build - Run app on devServer
# Comment this command for production build
#CMD ["npm","run","watch"]

# ERROR: out of memory
ENV NODE_OPTIONS=--max_old_space_size=8092




## Dev Server without Nginx
###############################

# DevEnv HTTPS Dev server run on 4200 (command: ng serve --ssl)
EXPOSE 4200
CMD ["npm","run","start"]


# Check if app is running. If not, shutdown the container
#HEALTHCHECK --interval=2m --timeout=5s --start-period=2m \
#  CMD nc -z -w5 127.0.0.1 4200 || exit 1





# Nginx - Serve the app - Production environment
#################################################
# Use official nginx image as the base image
#FROM nginx:latest

# Copy the build output to replace default nginx site
#COPY --from=build /usr/local/app /usr/local/app


# Nginx server listen on this 2 ports for http&https
# HTTP/HTTPS port for nginx
#EXPOSE 8080 8443


# Check if app is running. If not, shutdown the container
#HEALTHCHECK --interval=2m --timeout=5s --start-period=2m \
#  CMD nc -z -w5 127.0.0.1 8443 || exit 1

##> End Dev server with Nginx

