FROM node:latest as node

# Update image and install process manager
#RUN apk update && \
#    apk --no-cache upgrade \

RUN npm i npm@latest -g

# Build app with dev dependencies
FROM node as build

WORKDIR /usr/local/app

COPY package*.json tsconfig*.json ./

RUN npm install

COPY . ./

RUN npm run build


FROM node as prod

ENV NODE_ENV production

WORKDIR /srv/app

# Copy package configuration
COPY --chown=node:node --from=build /usr/local/app/package*.json ./
# Copy all the production-ready files to files
COPY --chown=node:node --from=build /usr/local/app/dist  ./dist

# Change ownership of root directory
RUN chown -R node:node /srv/app

# Expose HTTP/HTTPS server port
# Important: Expose command must be executed as root user
EXPOSE 3000 8443

# Use a non-root user
User node

# Install dependencies
RUN npm install --only=production && \
    npm cache clean --force

CMD ["npm","run","start:prod"]

# Check if app is running. If not, shutdown the container
#HEALTHCHECK --interval=2m --timeout=5s --start-period=2m \
#  CMD nc -z -w5 127.0.0.1 8443 || exit 1