FROM node:latest

RUN mkdir -p /usr/local/app

WORKDIR /usr/local/app

COPY package*.json /usr/local/app

# Install dependencies
RUN npm install

COPY . /usr/local/app

EXPOSE 3000

# Serve app
CMD ["npm", "start"]